services:
  application:
    image: ghcr.io/novatecconsulting/opentelemetry-training-application:latest
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    tty: true
    volumes:
      - ./:/workspace
    ports:
      - 5000:5000

